//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CM3036_Coursework___Kolesov1308140
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int matriculationNumber { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string componentOne { get; set; }
        public string componentTwo { get; set; }
        public string componentThree { get; set; }
        public string finalGrade { get; set; }

        public override string ToString()
        {
            return matriculationNumber + " - " + firstName + " " + lastName;
        }
    }

}
